theme: jekyll-theme-minimal
title: Dendro-Edu: 목재해부학 및 연륜연대법 자기주도 학습 오픈랩
description: 목재해부학 및 연륜연대법에 대해 궁금한 비전공자와 학생들을 대상으로 기본적인 개념을 다루고 공부하기 위해 만들어진 사이트 입니다.
description: 작성자: 최은비(En-Bi CHOI)
description: 업데이트: 2026.06.20
